### ISSUE TITLE
OpenError: IO error: lock ./0.db/LOCK: Resource temporarily unavailable

### ISSUE THREAD

**Issue by ekaitzht** [albertdb/Raft#1]
I have trying to implement my first time the Raft algorithm and I have done the steps that I have seen in the readme file. 
1. launch router.
2. launch 3 nodes with node server.js [id] tcp://localhost:12345 '["0","1","2"]' false
3. I launch a prueba.js to change the log to check that is working the Raft algorithm.

This the code of prueba.js

``` javascript

module.exports.clientId='0';
module.exports.routerAddress='tcp://localhost:12345';
module.exports.clusterMembers=['0','1','2'];
module.exports.debugClient=false;
module.exports.debugServer=false;
var client = require('./client.js');


client.put('foo', 'bar', function (err) {
    if (err) { console.log(err);}
        console.log("sale");
        });
```

But when I launch prueba.js I get this error.

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
OpenError: IO error: lock ./0.db/LOCK: Resource temporarily unavailable
    at /home/asier/Libro ZMQ/Raft/node_modules/level/node_modules/level-packager/node_modules/levelup/lib/levelup.js:119:34
    at /home/asier/Libro ZMQ/Raft/node_modules/level/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16






```

@albertdb

**Comment by albertdb** [comment]
Hola!

Each client has an instance of a Raft server with `id` equal to `module.exports.clientId`. So in this case there is a conflict because you already launched a standalone server with `id='0'` and since you are running all Raft servers in the same machine, the client with duplicate `id` cannot lock database because it's already in use by one of the standalone servers.

You have to either kill one of the standalone servers and use its `id` or to increase cluster size.

Any doubts, feel free to ask.

**Comment by ekaitzht** [comment]
-Ah ok when you launch a client.js behind the scenes is launching a "server.js" server isn't it? 
-If you launch prueba.js you dont need launch servers with "node server.js", isn it?

In summary If I want to add log entries to a client I should do this:
1. launch router
2. launch 3 different prueba.js with their respectives ids and one prueba.js that adds entries with client.put. 

Is right @albertdb? If it's right I will try to implement today or on Monday and I will tell you If could execute the algorithm.

PS: Gracias ando aqui en la upna ayudando a uno que esta con la tesis.

**Comment by albertdb** [comment]
Yes, you are correct and yes, that is one possible approach. But if you are only going to interact with the client layer from a single "node", it is better to run standalone (server.js) servers on the other nodes.
